name:                hui
version:             0.1.0.0
github:              "agcwall/hui"
license:             BSD3
author:              "Adam Wall"
maintainer:          "agcwall@gmail.com"
copyright:           "2019 Adam Wall"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/agcwall/hui#readme>

dependencies:
- base >= 4.7 && < 5
- gtk3
- mtl
- cairo
- text
- glib
- Win32
- containers

library:
  source-dirs: src

executables:
  demo-paint:
    main:                DemoPaint.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is DemoPaint
    dependencies:
    - hui

  demo-text:
    main:                DemoText.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is DemoText
    dependencies:
    - hui